# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.allansene.me" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Allan Sene Blog
  avatar: eu.jpg
  gravatar: "559c1397942f8d6da44d358e3dd307eb"
  description: "A website with blog posts and pages about big data, reactive systems and computer science" # used by search engines

  # Header and footer text
  header_text: >
     <p>Vagando <a href="http://www.goodreads.com/quotes/229-all-that-is-gold-does-not-glitter-not-all-those">(mas não perdido!)</a> pelos bosques dos sistemas reativos, enfrentando sanguinários processamentos de dados massivos (o tão famigerado Big Data) e grande adepto da poção de café das 14pm.</p>

  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: "allanseneoliveira@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "allan.sene"
  flickr:
  github: "allansene"
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/allansene"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  "http://stackoverflow.com/users/5712620/allan-sene"
  steam:
  tumblr:
  twitter: "allansene"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
